@echo off
rem ═══════════════════════════════════════════════════════════════════════════
rem  Zenith Windows Installer
rem  Run this ONCE from the project root to deploy all runtime helpers and
rem  the Cloudflare tunnel binary to %LOCALAPPDATA%\zenith\.
rem
rem  Usage (from the project root):
rem      infra\install-windows.bat
rem
rem  What it does:
rem   1. Creates %LOCALAPPDATA%\zenith\
rem   2. Writes config.cmd (bakes in the project root path)
rem   3. Copies run-*.cmd launchers
rem   4. Downloads cloudflared.exe (Cloudflare Tunnel, free, no account needed)
rem   5. Sets up the Python STT venv (if Python is available)
rem   6. Pulls required AI models via Ollama
rem   7. Builds the Node.js frontends (npm run build)
rem   8. Reports manual start instructions (autostart is disabled)
rem ═══════════════════════════════════════════════════════════════════════════
setlocal EnableDelayedExpansion

rem ── 0. Detect project root (where this script lives minus \infra) ─────────
set "SCRIPT_DIR=%~dp0"
rem Strip trailing backslash from SCRIPT_DIR
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"
rem Go one level up (infra → root)
for %%I in ("%SCRIPT_DIR%\..") do set "ZENITH_ROOT=%%~fI"

echo.
echo  ███████╗███████╗███╗   ██╗██╗████████╗██╗  ██╗
echo  ╚══███╔╝██╔════╝████╗  ██║██║╚══██╔══╝██║  ██║
echo    ███╔╝ █████╗  ██╔██╗ ██║██║   ██║   ███████║
echo   ███╔╝  ██╔══╝  ██║╚██╗██║██║   ██║   ██╔══██║
echo  ███████╗███████╗██║ ╚████║██║   ██║   ██║  ██║
echo  ╚══════╝╚══════╝╚═╝  ╚═══╝╚═╝   ╚═╝   ╚═╝  ╚═╝
echo.
echo  Windows Installer
echo  Project root : %ZENITH_ROOT%
echo  Deploy to    : %LOCALAPPDATA%\zenith\
echo.

rem ── 1. Create deploy directory ────────────────────────────────────────────
set "DEPLOY=%LOCALAPPDATA%\zenith"
if not exist "%DEPLOY%" mkdir "%DEPLOY%"

rem ── 2. Write config.cmd (bake in the real project root) ───────────────────
echo [1/8] Writing config.cmd ...
set "CFG=%DEPLOY%\config.cmd"
(
echo @echo off
echo rem Zenith runtime config — generated by install-windows.bat.
echo rem DO NOT edit manually — re-run install-windows.bat to regenerate.
echo.
echo set "ZENITH_ROOT=%ZENITH_ROOT%"
echo.
echo rem ── Load .env ──────────────────────────────────────────────────────────
echo for /f "usebackq tokens=1,* delims==" %%%%A in ^(
echo     `findstr /v "^#" "%ZENITH_ROOT%\.env" 2^^^>nul`
echo ^) do ^(
echo     set "%%%%A=%%%%B"
echo ^)
echo.
echo rem ── Defaults ───────────────────────────────────────────────────────────
echo if not defined PORT set PORT=3000
echo if not defined HOST set HOST=0.0.0.0
) > "%CFG%"
echo    Done: %CFG%

rem ── 3. Copy launcher scripts ──────────────────────────────────────────────
echo [2/8] Copying launcher scripts ...
set "SRC=%ZENITH_ROOT%\infra\launchers"
copy /y "%SRC%\run-api.cmd"    "%DEPLOY%\run-api.cmd"    >nul
copy /y "%SRC%\run-worker.cmd" "%DEPLOY%\run-worker.cmd" >nul
copy /y "%SRC%\run-stt.cmd"    "%DEPLOY%\run-stt.cmd"    >nul
copy /y "%SRC%\run-tunnel.cmd" "%DEPLOY%\run-tunnel.cmd" >nul
echo    Done.

rem ── 4. Download cloudflared.exe ───────────────────────────────────────────
echo [3/8] Checking cloudflared.exe ...
set "CF=%DEPLOY%\cloudflared.exe"
if exist "%CF%" (
    echo    Already present: %CF%
) else (
    echo    Downloading from GitHub releases ...
    powershell -NoProfile -Command ^
        "Invoke-WebRequest -Uri 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe' -OutFile '%CF%' -UseBasicParsing"
    if exist "%CF%" (
        echo    Downloaded: %CF%
    ) else (
        echo    WARNING: Download failed. Tunnel will not work until cloudflared.exe
        echo    is placed manually at: %CF%
        echo    Download URL: https://github.com/cloudflare/cloudflared/releases/latest
    )
)

rem ── 5. Python STT venv setup ──────────────────────────────────────────────
echo [4/8] Setting up Python STT venv ...
set "VENV=%ZENITH_ROOT%\services\inference\.venv"
set "VENV_PY=%VENV%\Scripts\python.exe"
set "REQS=%ZENITH_ROOT%\services\inference\requirements.txt"

where python >nul 2>&1
if errorlevel 1 (
    echo    WARNING: Python not found in PATH. STT sidecar will not work.
    echo    Install Python 3.10+ from https://python.org and re-run this installer.
    goto :skip_venv
)

if not exist "%VENV_PY%" (
    echo    Creating venv at %VENV% ...
    python -m venv "%VENV%"
)

echo    Installing Python dependencies (faster-whisper, edge-tts) ...
"%VENV_PY%" -m pip install --quiet --upgrade pip
"%VENV_PY%" -m pip install --quiet -r "%REQS%"
rem edge-tts is used for TTS but missing from requirements.txt — add it:
"%VENV_PY%" -m pip install --quiet edge-tts
echo    Python venv ready.
:skip_venv

rem ── 6. Pull AI Models ─────────────────────────────────────────────────────
echo [5/8] Pulling AI Models (llama3.2:3b and nomic-embed-text) ...
where ollama >nul 2>&1
if errorlevel 1 (
    echo    WARNING: Ollama not found in PATH. Please install from https://ollama.com
) else (
    echo    Pulling llama3.2:3b - LLM...
    call ollama pull llama3.2:3b
    echo    Pulling nomic-embed-text - Embeddings...
    call ollama pull nomic-embed-text
)

rem ── 7. Build Node.js frontends ────────────────────────────────────────────
echo [6/8] Building frontends (npm run build) ...
cd /d "%ZENITH_ROOT%"
call npm run build
if errorlevel 1 (
    echo    WARNING: Build had errors. Check output above.
) else (
    echo    Build complete.
)

rem ── 8. (Autostart removed) ──────────────────────────────────────────────
echo [7/8] Skipping autostart registration (removed by design).
echo    Start Zenith manually when you need it with infra\zenith-startup.bat

rem ── Done ──────────────────────────────────────────────────────────────────
echo [8/8] Installation complete!
echo.
echo  ┌─────────────────────────────────────────────────────────────────┐
echo  │  To start all services, run manually:                           │
echo  │    infra\zenith-startup.bat                                     │
echo  │                                                                 │
echo  │  Or run individual services:                                    │
echo  │    %DEPLOY%\run-api.cmd                     │
echo  │    %DEPLOY%\run-worker.cmd                  │
echo  │    %DEPLOY%\run-stt.cmd                     │
echo  │    %DEPLOY%\run-tunnel.cmd                  │
echo  │                                                                 │
echo  │  NOTE: Autostart is DISABLED. Zenith will NOT launch at logon.  │
echo  └─────────────────────────────────────────────────────────────────┘
echo.
pause
endlocal
