@echo off
rem Zenith — Cloudflare Tunnel launcher (deployed to %LOCALAPPDATA%\zenith\)
rem Exposes localhost:3000 publicly via a free *.trycloudflare.com URL.
rem The live URL is printed to this window and also saved to:
rem   %LOCALAPPDATA%\zenith\tunnel-url.txt
rem This file is generated by infra\install-windows.bat — do not edit manually.

call "%LOCALAPPDATA%\zenith\config.cmd"
if errorlevel 1 ( echo [run-tunnel] ERROR: config.cmd missing. Run install-windows.bat first. & pause & exit /b 1 )

set "CF=%LOCALAPPDATA%\zenith\cloudflared.exe"

if not exist "%CF%" (
    echo [run-tunnel] ERROR: cloudflared.exe not found at %CF%
    echo              It should have been downloaded by install-windows.bat.
    echo              Download manually from: https://github.com/cloudflare/cloudflared/releases/latest
    echo              Save as: %CF%
    pause
    exit /b 1
)

rem Wait for the API to be ready before exposing it
echo [run-tunnel] Waiting for API on http://127.0.0.1:%PORT% ...
:wait_loop
ping -n 2 127.0.0.1 >nul
curl -s -o nul -w "%%{http_code}" http://127.0.0.1:%PORT%/api/v1/health | findstr /c:"200" >nul 2>&1
if errorlevel 1 goto wait_loop
echo [run-tunnel] API is up. Starting Cloudflare Tunnel...

rem Log file captures the trycloudflare URL
set "LOGFILE=%LOCALAPPDATA%\zenith\tunnel.log"
echo. > "%LOGFILE%"

rem Run cloudflared; capture URL from its stderr log (redirecting stderr to stdout, and then to log file)
"%CF%" tunnel --url http://127.0.0.1:%PORT% --logfile "%LOGFILE%" --no-autoupdate
