@echo off
rem Zenith — STT/TTS sidecar launcher (deployed to %LOCALAPPDATA%\zenith\)
rem Runs faster-whisper + edge-tts Python sidecar on port 8090.
rem This file is generated by infra\install-windows.bat — do not edit manually.

call "%LOCALAPPDATA%\zenith\config.cmd"
if errorlevel 1 ( echo [run-stt] ERROR: config.cmd missing. Run install-windows.bat first. & pause & exit /b 1 )

set "VENV=%ZENITH_ROOT%\services\inference\.venv\Scripts\python.exe"
set "SCRIPT=%ZENITH_ROOT%\services\inference\stt_server.py"

if not exist "%VENV%" (
    echo [run-stt] ERROR: Python venv not found at %VENV%
    echo            Run:  cd %ZENITH_ROOT% ^& python -m venv services\inference\.venv
    echo            Then: %VENV% -m pip install -r services\inference\requirements.txt
    pause
    exit /b 1
)

echo [run-stt] Starting Whisper STT + edge-tts sidecar on port 8090 ...
"%VENV%" "%SCRIPT%"
