@echo off
rem Zenith — Worker launcher (deployed to %LOCALAPPDATA%\zenith\)
rem This file is generated by infra\install-windows.bat — do not edit manually.

rem Load project root and .env
call "%LOCALAPPDATA%\zenith\config.cmd"
if errorlevel 1 ( echo [run-worker] ERROR: config.cmd missing. Run install-windows.bat first. & pause & exit /b 1 )

cd /d "%ZENITH_ROOT%"
echo [run-worker] Starting background worker (purge jobs, risk scoring) ...
npm run start -w @zenith/worker
